# 2.1 ndarry多维数组

In [18]:
import numpy as np

## 创建array：从列表、元组、数组等数据容器

In [2]:
data1=[5,7,9,20]
array1=np.array(data1)
array1

array([ 5,  7,  9, 20])

In [4]:
data2=(5,7,9,20)
array2=np.array(data2)
array2

array([ 5,  7,  9, 20])

In [6]:
data3=((1,2,3,4),(5,6,7,8))
array3=np.array(data3)
array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
array3.shape

(2, 4)

In [8]:
array3.dtype

dtype('int32')

In [9]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones_like(array3,dtype=np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [17]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## python内置函数range()与np.arange()函数的对比

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
range(10)

range(0, 10)

In [21]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 创建正方形的n*n单位矩阵

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## array的数据属性

In [27]:
array4=np.array(np.arange(24),dtype=np.float64)
print(array4.ndim,array4.shape,array4.size,array4.dtype,array4.itemsize)

1 (24,) 24 float64 8


In [34]:
array5=array4.reshape(2,3,4).astype(np.int32)

In [35]:
array5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
print(array5.ndim,array5.shape,array5.size,array5.dtype,array5.itemsize)

3 (2, 3, 4) 24 int32 4


In [38]:
array5.astype(np.string_)

array([[[b'0', b'1', b'2', b'3'],
        [b'4', b'5', b'6', b'7'],
        [b'8', b'9', b'10', b'11']],

       [[b'12', b'13', b'14', b'15'],
        [b'16', b'17', b'18', b'19'],
        [b'20', b'21', b'22', b'23']]], dtype='|S11')

In [39]:
array5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
array5.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 数组合并与拆分

In [46]:
x=np.array(np.arange(12)).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
y=np.array(np.arange(12,24)).reshape(3,4)
y

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
np.concatenate([x,y],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
np.concatenate([x,y],axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [57]:
np.vstack([x,y])   # axis=0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
np.hstack([x,y]) # axis=1

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [62]:
z=np.array(np.arange(24)).reshape((4,6))
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [76]:
np.split(z,[2],axis=0)[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [77]:
np.split(z,[2,4],axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

## 多维数组的转置与轴对换

In [78]:
a=np.array(np.arange(12)).reshape(3,4)

In [79]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [85]:
a.transpose(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [89]:
b=np.array(np.arange(16)).reshape((2,2,4))

In [90]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [94]:
b.swapaxes(0,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

## numpy的随机函数

In [95]:
np.random.randint(100,200,size=(3,5))

array([[139, 152, 159, 182, 123],
       [112, 152, 112, 124, 166],
       [174, 169, 114, 185, 128]])

In [97]:
np.random.randn(2,4,6)

array([[[ 0.77298565, -0.15177999, -0.03993999,  0.1370259 ,
         -0.57453667,  1.32207052],
        [-2.01398805, -0.760631  , -1.04481558,  0.19119352,
         -0.42244969,  0.13392837],
        [-1.11811422, -1.58127921,  0.97214194, -1.22822532,
          0.15482849, -1.73976085],
        [ 1.00485166, -0.47723149,  0.3279221 ,  0.70029613,
          0.1367649 ,  0.18674874]],

       [[-1.03632427,  0.36766169,  0.69812817, -1.87432788,
          1.20903061,  0.40389915],
        [-0.29243089, -1.54214012,  0.93627304,  1.29644361,
          0.2512794 ,  1.09163595],
        [-1.16426558, -0.52645968, -1.91745275,  0.16428362,
         -0.25250416,  0.24983014],
        [-2.10430812,  0.44198479,  1.24832448, -1.26712668,
          0.59341939, -1.23372147]]])

In [98]:
np.random.normal(4,5,size=(3,5))

array([[ 7.81563237,  7.52523863, 11.97976085, -3.19835321, -3.72419356],
       [ 0.83253483,  0.59979656,  1.71829647, -3.42486295, -2.75553693],
       [-2.60718475,  6.88863922, -1.60745743, -5.19110888, -0.29088583]])

In [109]:
c=np.array(np.arange(10))

In [110]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
np.random.permutation(c)

array([0, 7, 1, 3, 2, 4, 6, 8, 5, 9])

In [112]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.random.shuffle(c)

In [118]:
c

array([5, 9, 7, 1, 3, 4, 6, 0, 8, 2])

In [124]:
np.random.poisson(lam=0.8,size=(3,5))

array([[2, 1, 2, 0, 0],
       [0, 1, 2, 3, 2],
       [0, 0, 0, 1, 0]])

In [125]:
np.random.uniform(0,10,size=(2,5))

array([[0.23787361, 7.94496557, 5.64920942, 1.62328985, 7.08275765],
       [1.4130139 , 1.8463153 , 6.10038792, 7.24997551, 9.33836825]])

# 2.2 数组的索引与切片
数组的切片与索引返回的都是原始数组的视图，在切片与索引上的修改会影响到原数组，array的.copy()方法可以复制数组得到新数组进行修改

## 布尔型索引：索引条件可以是任意的布尔表达式

In [132]:
fruits=np.array(["apple","banana","pear","banana","pear","apple","pear"])
datas=np.random.randint(-1,1,size=(7,5))

In [136]:
datas

array([[ 0,  0, -1, -1,  0],
       [-1,  0,  0,  0, -1],
       [ 0,  0,  0, -1,  0],
       [ 0,  0, -1,  0, -1],
       [-1,  0, -1, -1,  0],
       [ 0, -1,  0, -1, -1],
       [ 0,  0,  0, -1, -1]])

In [133]:
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [134]:
fruits=="pear"

array([False, False,  True, False,  True, False,  True])

In [139]:
datas[fruits=="pear"]

array([[ 0,  0,  0, -1,  0],
       [-1,  0, -1, -1,  0],
       [ 0,  0,  0, -1, -1]])

## 布尔型索引与切片索引的结合使用

In [144]:
datas[fruits=="pear",2:]

array([[ 0, -1,  0],
       [-1, -1,  0],
       [ 0, -1, -1]])

In [154]:
datas=array5.reshape(4,6)

In [160]:
datas

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## 花式索引与ndarray通用函数

In [156]:
datas[np.ix_([0,3],[1,2,4])]

array([[ 1,  2,  4],
       [19, 20, 22]])

In [161]:
x=datas[np.ix_([0,3],[1,2,4])]

In [163]:
x

array([[ 1,  2,  4],
       [19, 20, 22]])

In [165]:
np.square(x)

array([[  1,   4,  16],
       [361, 400, 484]], dtype=int32)

## 条件逻辑运算

In [170]:
a=np.array(range(1,5))
b=np.array(range(5,9))
condition=np.array([True,False,False,True])

In [171]:
np.where(condition,a,b)

array([1, 6, 7, 4])

In [172]:
np.array([(x if c else y) for (x,y,c) in zip(a,b,condition)])

array([1, 6, 7, 4])

In [174]:
arr=np.random.randn(4,4)
arr

array([[-0.10871791, -0.06961806,  2.1685846 , -0.3166553 ],
       [-0.23271649,  0.5241963 , -1.26639565,  2.26728995],
       [ 0.31071482,  2.16592909, -0.17262688, -0.31360883],
       [-1.6603685 , -1.1454188 , -0.66211727, -1.20812394]])

In [176]:
arr=np.where(arr>0,1,-1)
arr

array([[-1, -1,  1, -1],
       [-1,  1, -1,  1],
       [ 1,  1, -1, -1],
       [-1, -1, -1, -1]])

In [178]:
arr=np.random.randint(1,300,size=(4,6))
arr

array([[ 14,  40, 151, 134,  58,  34],
       [138,  90, 170, 153,  18, 181],
       [196, 238, 120, 282,  26, 144],
       [ 27, 142, 250, 181, 153,  73]])

In [179]:
np.where(arr>200,3,np.where(arr>100,2,1))

array([[1, 1, 2, 2, 1, 1],
       [2, 1, 2, 2, 1, 2],
       [2, 3, 2, 3, 1, 2],
       [1, 2, 3, 2, 2, 1]])

## 统计运算
主要的统计计算方法有
* 以下方法均可以指定轴上计算，一般axis=1是沿横轴计算，axis=0是沿纵轴计算

|方法|使用说明|
|-|-|
|sum|求和|
|mean|求均值|
|std, var|标准差和方差|
|min,max|最小值和最大值|
|argmin,argmax|最小值和最大值的索引|
|cumsum|累计和|
|cumprod|累计乘积|

In [191]:
arr=np.array(range(24)).reshape(4,6)

In [192]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [194]:
arr.mean()

11.5

In [199]:
arr.mean(axis=0)

array([ 9., 10., 11., 12., 13., 14.])

In [200]:
arr.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

In [203]:
arr.cumprod(axis=0)

array([[    0,     1,     2,     3,     4,     5],
       [    0,     7,    16,    27,    40,    55],
       [    0,    91,   224,   405,   640,   935],
       [    0,  1729,  4480,  8505, 14080, 21505]], dtype=int32)

In [204]:
arr.cumprod(axis=0)>500

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True]])

In [206]:
(arr.cumprod(axis=0)>500).sum()

7

In [207]:
bool_arr=arr.cumprod(axis=0)>500

In [209]:
bool_arr

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True]])

In [211]:
bool_arr.any()
# any 方法检测有一个或多个True

True

In [212]:
bool_arr.all()
# all 方法检测是否全部为All

False

## 集合运算
* 多维数组排序可以按照轴指定方向进行排序
* 集合运算 np.unique()求出array中唯一的元素
* 集合运算 np.inld()测试几个数组中是否有相同的值
* 集合运算 求交集、并集、集合差、交集取反等

In [213]:
a=np.array(np.random.randn(10))

In [215]:
a

array([-0.26087484,  0.29507825, -0.38149719,  1.5152537 , -1.75075699,
        0.03185574, -0.03729012,  0.14469111, -0.86423594, -0.13392622])

In [217]:
a.sort()

In [218]:
a

array([-1.75075699, -0.86423594, -0.38149719, -0.26087484, -0.13392622,
       -0.03729012,  0.03185574,  0.14469111,  0.29507825,  1.5152537 ])

In [221]:
b=np.array(np.random.randint(0,50,size=(3,5)))

In [222]:
b

array([[39, 34, 15, 37, 41],
       [19, 30,  8, 49,  3],
       [23, 21,  3, 18, 38]])

In [223]:
b.sort()

In [224]:
b

array([[15, 34, 37, 39, 41],
       [ 3,  8, 19, 30, 49],
       [ 3, 18, 21, 23, 38]])

In [227]:
b.sort(axis=0)

In [228]:
b

array([[ 3,  8, 19, 23, 38],
       [ 3, 18, 21, 30, 41],
       [15, 34, 37, 39, 49]])

In [230]:
a=np.array(np.random.randint(0,10,size=5))
b=np.array(np.random.randint(0,10,size=5))

In [231]:
a

array([7, 5, 7, 7, 6])

In [232]:
b

array([2, 0, 6, 7, 1])

In [234]:
np.in1d(a,b)

array([ True, False,  True,  True,  True])

In [235]:
np.unique(a)

array([5, 6, 7])

In [236]:
np.union1d(a,b)

array([0, 1, 2, 5, 6, 7])

In [237]:
np.intersect1d(a,b)

array([6, 7])

In [238]:
np.setdiff1d(a,b)

array([5])

In [239]:
np.setdiff1d(b,a)

array([0, 1, 2])

In [240]:
np.setxor1d(a,b)

array([0, 1, 2, 5])

In [241]:
np.setxor1d(b,a)

array([0, 1, 2, 5])

## 数组的存储于读取 np.save() / np.load()

## 数组的综合应用_图像变换

In [9]:
import numpy as np
import cv2

In [22]:
img=cv2.imread("./data/timg.jpg")
reversed_img_rgb=255-img
gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
reversed_img=255-gray
rgb=np.concatenate([img,reversed_img_rgb],axis=1)
gray=np.concatenate([gray,reversed_img],axis=1)
cv2.imshow("gray",gray)
cv2.imshow("rgb",rgb)
cv2.waitKey()
cv2.destroyAllWindows()